### ISSUE TITLE
Adding temporal aspects to iTown2: work description and effort quote

### ISSUE THREAD

**Issue by EricBoix** [MEPP-team/RICT#1]
## Problem description
[iTowsn2](https://github.com/iTowns/itowns2) misses a timeline slider. Study how to introduce this feature on the client side and what would be the API (REST?) on the backend side for things to work. 

## References
An inspiring source might be 3DUse way of doing things ?

**Comment by jailln** [comment]
Some information related to this issue can be found [here](https://github.com/MEPP-team/RICT/wiki/2017_06_12_-_Temporal_Itowns)
