### ISSUE TITLE
Realize the ability to display the city at a given state (N21)

### ISSUE THREAD

**Issue by EmmanuelSchmuck** [MEPP-team/RICT#14]
Refer to [Need 21](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need021.md)

**Comment by NikoSaul** [comment]
[Design Note](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Design/DesignNote021.md)

**Comment by EricBoix** [comment]
This issue was realized through [this itowns branch code](https://github.com/jailln/itowns/tree/3dtiles-temporal).
