### ISSUE TITLE
Realize a server to stream PostGIS 3D objects having a temporal dimension to the web (N17)

### ISSUE THREAD

**Issue by EmmanuelSchmuck** [MEPP-team/RICT#16]
* Refer to [Need 17](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need017.md)
* Lead is Jailln

**Comment by johnsamuelwrites** [comment]
Design: [discussion](https://github.com/MEPP-team/RICT/wiki/2017_07_13_-_ServerSideTemporal)

**Comment by jailln** [comment]
This issue has been implemented and the related design note can be found [here](https://github.com/MEPP-team/VCity/wiki/DesignNote017) (restricted access for now).

Next step is: implement it in the evolution of building-server/py3dtiles components.

**Comment by EricBoix** [comment]
This issue is realized with [this 3D-Tiles branch code](https://github.com/MEPP-team/py3dtiles/tree/3dtiles-temporal-v2).
