### ISSUE TITLE
FDE brain dump 

### ISSUE THREAD

**Issue by EricBoix** [MEPP-team/RICT#28]
Capture FDE know how on how to "temporalize" (associate temporality) CityGML data with change VCity's change detection algorithm.

**Comment by jailln** [comment]
The process could go:
 * Run change detection process algorithm of FPE (which outputs a list of ids of citygml that changed ?) on two versions of the city (e.g. 2009 and 2012) 
 * Edit the database to replace the citygml files that changed with the new ones (can be extracted from the citygml files with the ids from changedetection)
 * Update the dates of the citygml features in the database accordingly
