### ISSUE TITLE
Realize a decent packaging and provide first simple tests

### ISSUE THREAD

**Issue by EricBoix** [MEPP-team/RICT#31]
The [current version](https://github.com/MEPP-team/UDV/commits/master) of the [first prototype (Vilo3D demo application)](https://github.com/MEPP-team/UDV/tree/master/Vilo3D) is just a juxtaposition of files as opposed to being
 - tested 
 - properly packaged with npm (and webpack)...
 
Take some inspiration out of [iTowns](https://github.com/iTowns/) and provide :
  - [package.json](https://github.com/iTowns/itowns/blob/master/package.json)
  - some simple tests
  - some [Babel](https://github.com/iTowns/itowns/blob/master/.babelrc) stuf...

**Comment by EricBoix** [comment]
JGA: Document a little bit out of Oslandia's IRC feedback.

**Comment by Jeremy-Gaillard** [comment]
- [npm](https://www.npmjs.com/)
  - Dependency handling
  - Can define scripts to build, test, or start a test server
  - iTowns npm configuration: [package.json](https://github.com/iTowns/itowns/blob/master/package.json)

- [webpack](https://webpack.github.io/)
  - Application bundler: transform a list of source files into a static module
  - Can be enriched with various plug-ins (see below)
  - iTowns webpack configuration: [webpack.config.js](https://github.com/iTowns/itowns/blob/master/webpack.config.js)

- [babel](https://babeljs.io/)
  - Compile modern JavaScript (ES6 norm) into browser-ready JavaScript
  - iTowns babel config: [.bablerc](https://github.com/iTowns/itowns/blob/master/.babelrc), [webpack-babel.config.js](https://github.com/iTowns/itowns/blob/master/webpack-babel.config.js)

- [eslint](https://eslint.org/)
  - Linter for JavaScript
  - iTowns eslint config: [.eslintrc.js](https://github.com/iTowns/itowns/blob/master/.eslintrc.js), [.eslintignore](https://github.com/iTowns/itowns/blob/master/.eslintignore)

**Comment by EricBoix** [comment]
I'm trying to "import" a minimal subset of iTowns configuration files (for the above mentioned tools) to UDV. I created a small context [within my UDV fork](https://github.com/EricBoix/UDV) to explore this : in order to reproduce the error mentioned below just use
```
git clone https://github.com/EricBoix/UDV
cd UDV/UDV-Core
npm install
npm transpile
npm build.
```

With the help of some docs ([Transpiling ES6 to ES5 using babel](https://www.jonathan-petitcolas.com/2015/03/09/transpiling-es6-to-es5-using-babel.html), [ES6 Imports with Babel](http://www.pauleveritt.org/articles/pylyglot/es6_imports/) I was able to clear a few hurdles (probably with some kludges) like [using babel-present-env instead of es2015](https://github.com/rollup/rollup-plugin-babel/issues/120). 

We (with VJA) are now stuck on the following error (on `npm run transpile`):
```
Error: node_modules/ajv/dist/ajv.bundle.js: Can't resolve './compile/util' in '[...]/UDV-Core/node_modules/ajv/dist
```

Any clue for us ?

**Comment by jailln** [comment]
Inputs about test-suites and iTown's discussions about these can be found [here](https://github.com/iTowns/itowns/pull/581)

**Comment by EricBoix** [comment]
Refer to [new issue #34](https://github.com/MEPP-team/RICT/issues/34) for the remaining work.
