### ISSUE TITLE
Provide a tool to place and orient document in the scene (N032)

### ISSUE THREAD

**Issue by sophiaab** [MEPP-team/RICT#45]

**Comment by sophiaab** [comment]
[Need032](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need032.md)

**Comment by EricBoix** [comment]
Done by sophia/Laurent.

**Comment by mbredif** [comment]
I am quite interested in that feature, do you have an online demo of it ?

**Comment by jailln** [comment]
Hi Mathieu,
Sorry for the late response;
We do not have an accessible demo online yet but we will provide a video in the coming days. I will post the link here.

Meanwhile, you can find the code in [UDV](https://github.com/MEPP-team/UDV) (especially in the contribute extension) and [UDV-Server](https://github.com/MEPP-team/UDV-server).
