### ISSUE TITLE
Realize the camera control (ergonomic exploration of space) (N6)

### ISSUE THREAD

**Issue by EmmanuelSchmuck** [MEPP-team/RICT#9]
Refer to [Need 6](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need006.md)

**Comment by EricBoix** [comment]
JGA: there is already a prototype in late versions of iTowns (before it was removed) for the planar mode.

**Comment by EmmanuelSchmuck** [comment]
Controls are functional. Commenting/cleaning under way.
